### ISSUE TITLE
dispatch_semaphore_wait

### ISSUE THREAD

**Issue by mythodeia** [dvkch/SYAssetsLibrary#1]
Hello and thanks for some excellent piece of work.
I tried your code and i could not make it work when calling anything that had a 
dispatch_semaphore_wait inside.
When calling e.g albumsWithType everything froze without errors. I could not do nothing to the app.
then i changed the way these methods were written to see if i can remedy that.
for example here is the 
-(NSArray*)albumsWithType:(ALAssetsGroupType)albumType
method using a dispatch_async as well as a dispatch_semaphore together.

```
__block NSMutableArray *albums = [NSMutableArray array];
dispatch_semaphore_t sema = dispatch_semaphore_create(0);
dispatch_queue_t queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT,0);
dispatch_async(queue, ^{
    [self->_assetLibrary  enumerateGroupsWithTypes:albumType usingBlock:^(ALAssetsGroup *group, BOOL *stop) {
        if(group){
            NSURL *url = [group valueForProperty:ALAssetsGroupPropertyURL];
            if(url)  {
                SYAssetAlbum *album = [[SYAssetAlbum alloc] initWithURL:url andAssetLibrary:self->_assetLibrary];
                [albums addObject:album];
            }
        }else{
            dispatch_semaphore_signal(sema);
        }
    } failureBlock:^(NSError *error) {
        dispatch_semaphore_signal(sema);
    }];
});
dispatch_semaphore_wait(sema, DISPATCH_TIME_FOREVER);
dispatch_release(sema);
return [NSArray arrayWithArray:albums];
```

This works fine so i changed it wherever you used the dispatch_semaphore_wait(sema, DISPATCH_TIME_FOREVER);

please try it yourself so you can see that its not responding without my fix.
If you think i am in error please reply back. 

Again thanks a lot for contributing this excellent piece of code.
Regards
K.K

**Comment by dvkch** [comment]
Hi,

Thanks, although I haven't had time recently to maintain it and add all the possibilities I wanted :/ 

I had this issue using ios7 and Xcode 5, it worked before. I wanted to look into it but since its all beta I didn't right now. 

I tried an nslog in the foreach block (wherever I use semaphores), and nothing is logged even with pictures and access to library granted. But that's the thing, the user never granted it but a test on the authorization value seems to be positive against the whole access value. 

I think that's where all is freezing. 

I'll try and look into it in a couple of weeks (sorry I can't sooner :/) but if you have any solution or suggestion before please write it to me or post a pull request ! 

If I can do anything else to help don't hesitate and write me ! 

Have a very nice evening,

Stan

**Comment by dvkch** [comment]
Oops I just saw your solution..... I'll try it this weekend if I have time :) 

Stan

**Comment by mythodeia** [comment]
no worries....
you can test it anytime you can. i am looking forward to make this lib of yours even better. i know it currently did the trick in many aspects of my current app.

2 more questions:
1st:
i am confused about the requestPermission method, in the following couple of lines:

```
SEL authStatus = @selector(authorizationStatus);
if(![ALAssetsLibrary resolveClassMethod:authStatus]){
    if(block)
        block(ALAuthorizationStatusAuthorized);
    return;
}
```

this will always return true since it dynamically provides an implementation for a given selector for a class method. it does not check the auth status, right?

2nd:
you have a method named:
-(void)refresh;
which has a block reloadBlock.
where you planning on using this anywhere inside the lib?

i have made some more changes and if you want i can try to send you a pull request this weekend if i have the time.

Thats all.
Thanks again for sharing and taking the time to answer
K.K
